#! /bin/sh

# Start applications from ~/.local/bin/autostart
autostart &

# bspwm settings
bspc monitor -d 1 2 3 &
bspc config border_width         2
bspc config window_gap          10
bspc config split_ratio          0.52

bspc config pointer_modifier super
bspc config borderless_monocle   true
#bspc config gapless_monocle      true
#bspc config focus_follows_pointer true

bspc config normal_border_color "#5E81AC"
bspc config active_border_color "#5E81AC"
bspc config focused_border_color "#81a1c1"
bspc config presel_feedback_color "#88C0D0"

bspc rule -a Zathura state=tiled
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# colors template
#nord polar night #2e3440 #3b4252 #434c5e #4c566a
#nord snow storm #d8dee9 #e5e9f0 #eceff4
#nord frost #8fbcbb #88c0d0 #81a1c1 #5e81ac
#nord aurora #bf616a #d08770 #ebcb8b #a3be8c #b48ead
